apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gabbology-production
  labels:
    name: gabbology-production
spec:
  tls:
    - hosts:
        - "gabbology.com"
      secretName: local-gabbology-com-tls
  rules:
    - host: "gabbology.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: gabbology
                port:
                  number: 80
