apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-gabbology-com
  namespace: default
spec:
  secretName: local-gabbology-com-staging-tls
  issuerRef:
    name: gabbology-staging
    kind: ClusterIssuer
  commonName: "gabbology.com"
  dnsNames:
    - "gabbology.com"
