apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbology
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: gabbology
spec:
  project: default

  sources:
    - repoURL: git@github.com:GabrielBernard/gabbology.git
      targetRevision: main
      path: k8s/cert-manager

    - repoURL: git@github.com:GabrielBernard/gabbology.git
      targetRevision: main
      path: k8s/gabbology

  destination:
    server: https://kubernetes.default.svc
    namespace: gabbology

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

  revisionHistoryLimit: 3
