name: package-server
run-name: Package server

permissions:
  packages: write

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'
      - 'app/**'
      - '!app/.vscode/**'
      - '!app/.gitignore'
      - '!app/README.md'
      - 'docker/**'
      - 'server/**'
      - '!server/.vscode/**'
      - '!server/.gitignore'
      - '!server/README.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build-and-package-server:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build NextJS app
        uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Build NextJS app
        run: |
          cd app
          npm ci
          npm run build
      - name: Install arm64 linker, tools and libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ gcc-aarch64-linux-gnu libc6-dev-arm64-cross
      - name: Update Rust toolchain
        run: |
          rustup update
          rustup component add clippy rustfmt
          rustup target add aarch64-unknown-linux-gnu
      - name: Rust Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: Lint server
        run: |
          cd server
          cargo fmt -- --check
          cargo clippy -- -D warnings
      - name: Test server
        run: |
          cd server
          cargo check
          cargo test --all
      - name: Build server
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
          CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++
        run: |
          cd server
          cargo build --release --target aarch64-unknown-linux-gnu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/arm64
          build-args: |
            ASSETS=app/public/assets
            NEXT_APP=app/.next
            GABBOLOGY_SERVER=server/target/aarch64-unknown-linux-gnu/release/gabbology-server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
